# -*- coding: utf-8 -*-
"""app1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/166A0GZVnMKeVfCDJ6Atr0IJqrVwjoV9K
"""

import streamlit as st
import pandas as pd
import numpy as np
import pickle

pickle_in = open('LR.pkl','rb')
LR = pickle.load(pickle_in)

def prediction():
    prediction = LR.predict([[pclass,sex,age,sibsp,parch,fare,embarked]])
    print(prediction)
    return prediction

def main():
  st.title("titanic prediction")
  pclass=st.text_input("pclass")
  sex=st.text_input("sex")
  age=st.text_input("age")
  sibsp=st.text_input("sibsp")
  parch=st.text_input("parch")
  fare=st.text_input("fare")
  embarked=st.text_input("embarked")
  result=""
  if st.button("predict"):
    result=prediction()
  st.success('The output is {}'.format(result))
if __name__=='__main__':
  main()

